commands: [
	["quit",     "killall ren",          "Q"],
	["browser",  "brave-browser",        "B"],
	["terminal", "kitty",                "T"],
	["volume",   "kitty alsamixer -c 1", "V"],
	["editor",   "kitty nvim",           "E"],
]

font-size: 24
font-path: "JuliaMono.ttf"

exit-on-key: 1
window-width: 480

background-color:  "#242430"
command-color:     "#696969"
text-color:        "#fafafa"
key-color:         "#fba0c0"

